const resList = [
  // {
  //   cardType: "topCollection",
  //   layoutAlignmentType: "VERTICAL",
  //   data: {
  //     type: "topCollection",
  //     subtype: "image",
  //     data: {
  //       displayName: "Biryani",
  //       id: 83649,
  //       count: 175,
  //       identifier: "",
  //       description:
  //         "Taste these delectable classics, delectable biryanis to make your day.",
  //       webCollectionHeader:
  //         "v1674029961/PC_Creative%20refresh/3D_bau/collections_new/Biriyani.png",
  //       webMastHead:
  //         "v1674029961/PC_Creative%20refresh/3D_bau/collections_new/Biriyani.png",
  //       appMastHead:
  //         "v1674029961/PC_Creative%20refresh/3D_bau/collections_new/Biriyani.png",
  //     },
  //   },
  //   parentWidget: false,
  // },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "204708",
        name: "Oziano",
        uuid: "3d962d5a-e0a5-47bc-80ec-61359f0fa936",
        city: "1",
        area: "Marathahalli",
        totalRatingsString: "",
        cloudinaryImageId: "lqflyazsouh5vgsakwql",
        cuisines: ["Bengali", "Biryani", "Chinese", "North Indian"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 44,
        minDeliveryTime: 44,
        maxDeliveryTime: 44,
        slaString: "44 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "oziano-new-area-test-prod-area",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "AECS Layout",
        parentId: 14537,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6500,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6500,
          message: "",
          title: "Delivery Charge",
          amount: "6500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7953260~p=2~eid=0000018a-1796-7ead-1c6f-2bb4003d023a~srvts=1692612853421~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=204708&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 44,
          minDeliveryTime: 44,
          maxDeliveryTime: 44,
          lastMileTravel: 0,
          lastMileDistance: 8,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "256960",
        name: "Shanmukha Restaurant",
        uuid: "f31cc794-8f6b-4a10-92c5-72d2c6e87c51",
        city: "1",
        area: "Brookefield",
        totalRatingsString: "",
        cloudinaryImageId: "abcktugmzdvmc8cvaxre",
        cuisines: [
          "Biryani",
          "Andhra",
          "South Indian",
          "North Indian",
          "Tandoor",
          "Chinese",
          "Beverages",
          "Desserts",
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "shanmukha-restaurant-whitefield-whitefield",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Kundalahalli",
        parentId: 9954,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6500,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6500,
          message: "",
          title: "Delivery Charge",
          amount: "6500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7960001~p=3~eid=0000018a-1796-7ead-1c6f-2bb5003d0377~srvts=1692612853421~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              description: "",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        lastMileTravelString: "7.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=256960&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 0,
          lastMileDistance: 7.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "699448",
        name: "Advaita restaurant",
        uuid: "82dd61d6-5b3a-4b59-9321-335f8351e28e",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "",
        cloudinaryImageId: "c96592336a962012b93ef15507ce6b1a",
        cuisines: ["Biryani", "South Indian", "Andhra"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "advaita-restaurant-whitefield-whitefield",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Nagondanahalli Main Rd",
        parentId: 418032,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 9500,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9500,
          message: "",
          title: "Delivery Charge",
          amount: "9500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7931279~p=4~eid=0000018a-1796-7ead-1c6f-2bb6003d0463~srvts=1692612853421~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=699448&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 0,
          lastMileDistance: 9.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "285116",
        name: "Dindigul Thalappakatti",
        uuid: "ad51ebae-f00b-44c9-89f5-1a2767b9950e",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "",
        cloudinaryImageId: "qcoeeteu67eei7wlomdp",
        cuisines: [
          "Biryani",
          "Barbecue",
          "South Indian",
          "Chinese",
          "North Indian",
        ],
        tags: [],
        costForTwo: 60000,
        costForTwoString: "₹600 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "dindigul-thalappakatti-mahadevpura-mahadevpura",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Garudacharpalya",
        parentId: 332,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6000,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6000,
          message: "",
          title: "Delivery Charge",
          amount: "6000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7823867~p=10~eid=0000018a-1796-7ead-1c6f-2bbc003d0a13~srvts=1692612853421~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.8 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=285116&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 0,
          lastMileDistance: 4.8,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.8",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "436021",
        name: "Ponnusamy Hotel",
        uuid: "c32d7051-7e0a-447d-a6ce-4053e3156079",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "",
        cloudinaryImageId: "lghjedrfnslwe4mi3xlw",
        cuisines: ["Biryani", "South Indian", "Chettinad"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "ponnusamy-hotel-whitefield-whitefield",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Forum Shantiniketan Mall",
        parentId: 4205,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6000,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6000,
          message: "",
          title: "Delivery Charge",
          amount: "6000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7779090~p=12~eid=0000018a-1796-7ead-1c6f-2bbe003d0c2e~srvts=1692612853421~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.3 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=436021&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 0,
          lastMileDistance: 4.3,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.7",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "221738",
        name: "Meghana Foods",
        uuid: "106f4556-6804-4554-8c68-ee875d6acf65",
        city: "1",
        area: "Brookefield",
        totalRatingsString: "",
        cloudinaryImageId: "aqsnrylokzpn45qhg1pb",
        cuisines: [
          "Biryani",
          "Andhra",
          "South Indian",
          "North Indian",
          "Chinese",
          "Seafood",
        ],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "meghana-foods-mahadevpura-mahadevpura",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Mahadevpura",
        parentId: 635,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 5900,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5900,
          message: "",
          title: "Delivery Charge",
          amount: "5900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=221738&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 0,
          lastMileDistance: 6.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "222271",
        name: "Hyderabadi Kitchen",
        uuid: "e88fbc50-cf84-47d7-9464-769d7b094f6f",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "",
        cloudinaryImageId: "uupnrcypkxjioxmwxnmf",
        cuisines: ["Biryani"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "shahi-dum-biriyani-whitefield-whitefield",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Rajapalya",
        parentId: 105220,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=222271&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 0,
          lastMileDistance: 2.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.5",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "375067",
        name: "Andhra Gunpowder",
        uuid: "b266987c-720b-4ab4-89c4-17da60d1a318",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "",
        cloudinaryImageId: "hcpqjl0dcgvwxpjfnysa",
        cuisines: ["Andhra", "Biryani", "South Indian"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "andhra-gunpowder-mahadevpura-mahadevpura",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "ITPL Main Road",
        parentId: 10496,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 3400,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3400,
          message: "",
          title: "Delivery Charge",
          amount: "3400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              description: "",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=375067&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 0,
          lastMileDistance: 3,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "45760",
        name: "Andhra Biryanis",
        uuid: "1f644ca2-ad6f-4a97-8d97-ff140c985087",
        city: "1",
        area: "Whitefield",
        totalRatingsString: "",
        cloudinaryImageId: "czk4fwb0l3hbx6ljol62",
        cuisines: ["Andhra", "Biryani", "Hyderabadi", "Chinese", "Tandoor"],
        tags: [],
        costForTwo: 48000,
        costForTwoString: "₹480 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "andhra-biryanis-whitefield-whitefield",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Patandur Agrahara",
        parentId: 7444,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 5300,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5300,
          message: "",
          title: "Delivery Charge",
          amount: "5300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              description: "",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        lastMileTravelString: "5.9 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=45760&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 0,
          lastMileDistance: 5.9,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "222837",
        name: "Potful - Claypot Biryanis",
        uuid: "42828768-0847-44b3-af7d-2902ddacbb5f",
        city: "1",
        area: "Brookefield",
        totalRatingsString: "",
        cloudinaryImageId: "d874577e3c5ea2f730f6e22ceeae7ad4",
        cuisines: ["Biryani", "Kebabs", "North Indian", "Mughlai"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 52,
        minDeliveryTime: 52,
        maxDeliveryTime: 52,
        slaString: "52 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "potful-whitefield-whitefield",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Graphite India Main Road",
        parentId: 160121,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 8500,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8500,
          message: "",
          title: "Delivery Charge",
          amount: "8500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.3 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=222837&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 52,
          minDeliveryTime: 52,
          maxDeliveryTime: 52,
          lastMileTravel: 0,
          lastMileDistance: 7.3,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "377549",
        name: "RNR Biryani - Taste of 1953",
        uuid: "d5032f98-416d-49ed-b43f-f8c60dc91206",
        city: "1",
        area: "KR Puram",
        totalRatingsString: "",
        cloudinaryImageId: "oard3jyt2excnbv4afsd",
        cuisines: ["Biryani", "South Indian", "Kebabs"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "rnr-biryani---taste-of-1953-battarahalli-battarahalli",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Old Madras Road",
        parentId: 11620,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 3400,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3400,
          message: "",
          title: "Delivery Charge",
          amount: "3400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=377549&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 0,
          lastMileDistance: 3.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "254632",
        name: "Kallayi Family Restaurant",
        uuid: "ebc3d93a-68a2-464c-a0e7-f96f58197387",
        city: "1",
        area: "Kr Puram",
        totalRatingsString: "",
        cloudinaryImageId: "h4f36iipmwf7a5ova4ku",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: "20 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "kallayi-family-restaurant-battarahalli-battarahalli",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Swathantra Nagar",
        parentId: 114043,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2800,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.4 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=254632&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 0,
          lastMileDistance: 1.4,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "16395",
        name: "Kabab Magic (Outer Ring Road)",
        uuid: "6cc393df-00d0-4708-9c23-77af21565a75",
        city: "1",
        area: "Mahadevpura",
        totalRatingsString: "",
        cloudinaryImageId: "nbg6fvp8efekdf1jbqjg",
        cuisines: ["North Indian", "Chinese"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "kebab-magic-doddanakundi-mahadevpura",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Doddanekkundi",
        parentId: 527,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6500,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6500,
          message: "",
          title: "Delivery Charge",
          amount: "6500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.1 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=16395&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 0,
          lastMileDistance: 7.1,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "37909",
        name: "Nizam's Biryani House",
        uuid: "b94239b5-df53-44bd-8e20-a50beb605cd7",
        city: "1",
        area: "Marathahalli",
        totalRatingsString: "",
        cloudinaryImageId: "vte3xrjbp9rh7htuokf0",
        cuisines: [
          "Andhra",
          "Beverages",
          "Biryani",
          "Chinese",
          "Desserts",
          "Mughlai",
          "North Indian",
          "South Indian",
        ],
        tags: [],
        costForTwo: 60000,
        costForTwoString: "₹600 FOR TWO",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        slaString: "40 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "nizams-biryani-house-marathahalli-marathahalli",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Aswath Nagar",
        parentId: 7406,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 9500,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9500,
          message: "",
          title: "Delivery Charge",
          amount: "9500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.7 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=37909&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 40,
          minDeliveryTime: 40,
          maxDeliveryTime: 40,
          lastMileTravel: 0,
          lastMileDistance: 9.7,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.7",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];

export default resList;
